### ISSUE TITLE
Property 'decodeTransactions' does not exist on type 'AppStoreServerAPI'.ts(2339)

### ISSUE THREAD

**Issue by josephkkin** [agisboye/app-store-server-api#16]
The types definition files needs to be updated for the latest updates.

**Comment by josephkkin** [comment]
After a bit of investigating the issue, noticed that the documentation of the usage of decodeTransactions on the NPM repo site is different from the README in the Git repo.

The NPM site mentions it as follows.
`
// Decoding not only reveals the contents of the transactions but also verifies that they were signed by Apple.
const transactions = await api.decodeTransactions(response.signedTransactions)
`

In the Git README it is documented as follows.
`
// Decoding not only reveals the contents of the transactions but also verifies that they were signed by Apple.
const transactions = await decodeTransactions(response.signedTransactions)
`

**Comment by agisboye** [comment]
The README has been updated on npm. 😊
