### ISSUE TITLE
Filter Transactions in "DESCENDING" order

### ISSUE THREAD

**Issue by pnostudiodeveloper** [agisboye/app-store-server-api#18]
By default, it appears that Apple provides the Transaction history with the oldest transactions first.

They provide a way to filter transactions using the DESCENDING value in the 'sort' parameter that returns the newest transactions first.
https://developer.apple.com/documentation/appstoreserverapi/get_transaction_history

Is there a way to pass this filter value in the `api.getTransactionHistory(orderId)` call?

Thank you!

**Comment by agisboye** [comment]
The sort and filter options were announced during WWDC 2022. I'm working on adding them as we speak. 😊

**Comment by agisboye** [comment]
This is now supported in [v0.5.0](https://github.com/agisboye/app-store-server-api/releases/tag/v0.5.0).
