### ISSUE TITLE
General question on how your library was created

### ISSUE THREAD

**Issue by jmjava** [agisboye/app-store-server-api#19]
Sorry I know this question is not directly related to your project.  Just you are one of the few people I have found that have created any code for this API.  I need to do something similar in Java but I am not finding any official specification for the App Store Notifications v2.  Is there an openAPI spec for this library?

**Comment by agisboye** [comment]
Hi,

I'm not aware of any OpenAPI spec. I used Apple's documentation here: [https://developer.apple.com/documentation/appstoreservernotifications/app_store_server_notifications_v2](https://developer.apple.com/documentation/appstoreservernotifications/app_store_server_notifications_v2)

The notification history and testing APIs are documented here: [https://developer.apple.com/documentation/appstoreserverapi](https://developer.apple.com/documentation/appstoreserverapi)

**Comment by jmjava** [comment]
Thanks so much...It's crazy that Apple makes you parse html pages.  I coded
by hand using your classes as a guide.
