### ISSUE TITLE
The token always is invalid

### ISSUE THREAD

**Issue by yuanpli** [agisboye/app-store-server-api#2]
Hello,

Happy to see there is a client lib to communicate with app store server API. Thanks for your contribution.

Today, I have tried with this library, but I always got the 401 error. 
The code I tested is 

```
const KEY = `-----BEGIN PRIVATE KEY-----
xxxxxxx
-----END PRIVATE KEY-----`

const KEY_ID = "xxx";
const ISSUER_ID = "xxxx";
const APP_BUNDLE_ID = "xxx";

const ServerApi = new AppStoreServerAPI(
  KEY, KEY_ID, ISSUER_ID, APP_BUNDLE_ID, Environment.Sandbox
);
let results = await ServerApi.getTransactionHistory(1000000944298944);

```
I have debugged the code, it seems that the jwt lib `jose` return an invalid token. After replace with `jsonwebtoken`, the token is valid.

Could you kindly help double-check if this is an existing issue? Thanks! And hope there will be a correction. Thanks!

**Comment by agisboye** [comment]
Hi,

I'm not sure what you mean by an invalid token. Could you point to where in the code this happens and provide an example of what an invalid token looks like?

**Comment by yuanpli** [comment]
Hi,

The invalid token that I mentioned is in the response got from App Store Server when invoking an API method(like api.getTransactionHistory()). And the HTTP status is 401

```
The request is unauthorized; the JSON Web Token (JWT) is invalid.
```

**Comment by agisboye** [comment]
There is currently a bug in the API. If the purchase belongs to an Apple ID that has been deleted, the API will return the error that you've encountered (HTTP 401) when it should be returning  [AccountNotFoundError](https://developer.apple.com/documentation/appstoreserverapi/accountnotfounderror).

I've reported this to Apple and they're working on a fix.

**Comment by yuanpli** [comment]
I am afraid it is not the root cause. I tested in postman. The API is working well with a token that generated with `[jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken)` manually.

**Comment by agisboye** [comment]
Could you try inspecting the token that the library generates? See [getToken](https://github.com/agisboye/app-store-server-api/blob/9ac7d28071df92f41168ba9c47ea8e02086983e1/src/AppStoreServerAPI.ts#L128)

Also, is there a possibility that you somehow have an older version of `jose` installed? You could try deleting your node_modules and reinstalling.

**Comment by yuanpli** [comment]
> 

I have tried with some old versions jose@4.x.x. Unfortunately, all failed.

**Comment by agisboye** [comment]
I'll gladly look into any issue but you're going to have to make an effort and help me figure things out. As far is I know you're the only one seeing this. I use this library in production on multiple projects and haven't encountered the problem you've described.

Opening issues all across GitHub is not going to allow people to solve this issue for you.

**Comment by yuanpli** [comment]
Upgrade node version. The issue is resolved. Thanks for your support!

**Comment by turbobuilt** [comment]
Same issue

**Comment by turbobuilt** [comment]
Ok on my end I had an in-app-purchase token instead of an app store connect api token

**Comment by adriancable** [comment]
@yuanpli - jose generates mangled signatures for ES256 (used for the App Store Server API) on Node 12.15 and prior, because it uses a feature only added in Node 12.16, without checking it's available. You can switch to jsonwebtoken instead, which works correctly on Node 12.15.

**Comment by agisboye** [comment]
Node 15.6.0 was chosen as the minimum required version because it introduces [X509Certificate](https://nodejs.org/api/crypto.html#class-x509certificate), which this package uses. Node 12 never was (and never will be) supported.

**Comment by adriancable** [comment]
@agisboye - my apologies! My comment (albeit true) is therefore not relevant here.
