### ISSUE TITLE
Not an Issue but a Thank You

### ISSUE THREAD

**Issue by grantmk** [agisboye/app-store-server-api#20]
Just wanted to leave a comment thanking you for creating this library. I'm using it only for one function - verify Apple Server notifications. After a week of CrApples IAP docs I'm so glad I found this library!

**Comment by agisboye** [comment]
Hi Grant,
I appreciate your comment. Thanks! 
The APIs are a little convoluted (although much better than what we had before). The ability to verify notifications using this library is just a fortunate coincidence of Apple using the same signature scheme for notifications and App Store transactions. 😊
