### ISSUE TITLE
App Store Server Notifications 2.7 adds new field "summary" mutually exclusive with "data"

### ISSUE THREAD

**Issue by willbattel** [agisboye/app-store-server-api#24]
We're not using this yet ourselves but I wanted to put this on the radar for those developers who will want to take advantage of this new feature.

https://developer.apple.com/documentation/appstoreservernotifications/responsebodyv2decodedpayload
https://developer.apple.com/documentation/appstoreservernotifications/summary
https://developer.apple.com/documentation/appstoreserverapi/extend_subscription_renewal_dates_for_all_active_subscribers

**Comment by agisboye** [comment]
Thanks for the heads up, Will! It looks like they also added a `RENEWAL_EXTENSION` notification type.

I'm concerned it'll be difficult supporting this without causing breaking changes. If you or anybody else wants to give it a go, please feel free to submit a PR.

**Comment by willbattel** [comment]
Sure thing. Maybe down the road if nobody else gets to it, but as I said we're currently in no rush to support this. I think it's expected that this would require breaking changes, as you now have to make `data` nullable. I don't think that's a problem though so long as the library remains compliant with semver and the breaking changes are clearly noted.
