### ISSUE TITLE
As soon as i add the await decodeNotificationPayload(signedPayload) call in to my code, firebase functions wont deploy

### ISSUE THREAD

**Issue by jhonatan-3a** [agisboye/app-store-server-api#28]
its giving me the error Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error as soon as i add this function to my codebase, any reasons why?

**Comment by agisboye** [comment]
This sounds like an issue with Firebase functions. Can you specify which version of Node.js to use? Note that version 15.6.0 or later is required.

**Comment by jhonatan-3a** [comment]
your probably right, im using v16, tried using 18 buts also failing

**Comment by jhonatan-3a** [comment]
hey, @nicoladaniello  i have that line comented out for now, will check after lunch and tell you asap what i got
