### ISSUE TITLE
Get transaction history with wrong query parameter revision

### ISSUE THREAD

**Issue by yuanpli** [agisboye/app-store-server-api#3]
Hello,

The query parameter `revision` name in the API getTransactionHistroy is wrong. It should be `revision` not `query`
See the API from apple doc.
![image](https://user-images.githubusercontent.com/13729335/150927175-a7189286-b276-4e14-b27f-693f769a5835.png)

In the current implementation, the query field is a typo.
```
 async getTransactionHistory(originalTransactionId: string, revision?: string): Promise<HistoryResponse> {
    const query = revision ? `?query=${revision}` : ""
    return this.makeRequest(`${this.baseUrl}/inApps/v1/history/${originalTransactionId}${query}`)
  }
```

**Comment by agisboye** [comment]
Thanks! Fixed in fecd12ab91420ed326faa81e2287bf7cd13cb026
