### ISSUE TITLE
Any chance to add 403 into error path of makeRequest?

### ISSUE THREAD

**Issue by lucaspang** [agisboye/app-store-server-api#33]
I am currently developing subscription extension and some errors are from status code 403
4030004: Subscription Extension Ineligible
4030005: Subscription Max Extension
4030007: Family Shared Subscription Extension Ineligible
Right now all these errors are grouped to unknown error. 
Thank you!

**Comment by agisboye** [comment]
Have a look at [AppStoreError](https://github.com/agisboye/app-store-server-api/blob/main/src/Errors.ts). You can check the `errorCode` property to see which error you have.

**Comment by lucaspang** [comment]
Thank you for replying. If the result.status is 403 in [makeRequest(Line 150)](https://github.com/agisboye/app-store-server-api/blob/8c39c4ecf6bddb6147d8c97fe0ceeca74a1de659/src/AppStoreServerAPI.ts#L150C16-L150C16), it will fallback to default case to return a general unknown error, instead of the AppStoreError, only 400, 404 and 500 will pass along with the apple errorCode.

**Comment by agisboye** [comment]
Good point 😊 I've added both 403 and 429. 
Apple doesn't have an overview over all the status codes they use so if I've missed any other ones, let me know.
