### ISSUE TITLE
Missing latest tag on release 0.12.0

### ISSUE THREAD

**Issue by fariassdev** [agisboye/app-store-server-api#38]
Hi August.

I think there is missing the latest tag on the release 0.12.0, so the repo is still showing in the 0.11.1 as latest version.

<img width="371" alt="Screenshot 2023-10-05 at 10 00 43" src="https://github.com/agisboye/app-store-server-api/assets/19715763/a013c379-78e9-4f7b-8591-7b542c32c2d3">

Thanks for your time!

**Comment by agisboye** [comment]
Fixed. Thanks!
