### ISSUE TITLE
validating certificate chain

### ISSUE THREAD

**Issue by pnico** [agisboye/app-store-server-api#4]
https://github.com/agisboye/app-store-server-api/blob/55f143ed23e1a4b3f0584daa659d0690cf971a7f/src/Decoding.ts#L75

Is checkIssued() here verifying the certificates with public key, or just checking that it's the right issuer?

**Comment by pnico** [comment]
Is this enough? Couldn't someone just create a self-signed certificate with the same issuer data as Apple's intermediate certificate, and sign the last certificate with that (the one used to sign the payload)?

**Comment by agisboye** [comment]
I think you might be right. [X509_check_issued](https://github.com/nodejs/node/blob/66da32c045035cf2710a48773dc6f55f00e20c40/deps/openssl/openssl/crypto/x509/v3_purp.c#L905) does a number of checks but checking the actual signature is not one of them, apparently.

What does it even mean for a cert to be issued by another if it has not been signed by the issuing cert? This does not exactly inspire confidence in the crypto module.

Do you agree that the following would fix the issue?
https://github.com/agisboye/app-store-server-api/commit/9d4b662c81c28307af580e15c34294d995380f86

**Comment by agisboye** [comment]
That makes sense but it is obviously not what we want in this case. I've merged the fix and tagged it as v0.2.10. Thanks for bringing it to my attention!
