### ISSUE TITLE
Get Refund History

### ISSUE THREAD

**Issue by friedScotch** [agisboye/app-store-server-api#45]
Hi,

I am just wondering if you are planning on adding a getRefundHistory function as well.

Thanks!

**Comment by agisboye** [comment]
Hi,
I'm not planning on adding it but I'd be happy to accept a PR that does. It's very similar to transaction history.

**Comment by friedScotch** [comment]
Hey, thanks for the prompt reply.

I'll close the issue for now, if I get around to it I'll create a PR for it
