### ISSUE TITLE
Sample Payload to Test

### ISSUE THREAD

**Issue by csarigumba** [agisboye/app-store-server-api#51]
Do you have sample payload to test the below decoding? Its because it is difficult to simulate a real request. Thanks for the help.

```
const transactionInfo = await decodeTransaction(item.signedTransactionInfo)
const renewalInfo = await decodeRenewalInfo(item.signedRenewalInfo)
```

**Comment by agisboye** [comment]
No, sorry. I'm not fully confident that sharing a details about a purchase doesn't carry any implications.
You should be able to easily do an in-app purchase yourself (it could be in the sandbox), which will give you a payload to work with.
