### ISSUE TITLE
Is it possible to check if the setup works

### ISSUE THREAD

**Issue by zawoj** [agisboye/app-store-server-api#52]
First: Thanks for the lib, helps a lot.

Is there any way to check the connection to apple without having to give transactionID ?

**Comment by agisboye** [comment]
Hi @zawoj,
Help me understand what you're trying to accomplish. Do you want to test whether key works?

**Comment by zawoj** [comment]
Yes, thats correct.

**Comment by zawoj** [comment]
Yes, that's what I'm doing now. I was just curious if there is a better way
Thanks !
