### ISSUE TITLE
Upgrade to Minimum Node.js v18 (LTS) and Use node-fetch as a Polyfill

### ISSUE THREAD

**Issue by KROSF** [agisboye/app-store-server-api#58]
### Summary
The project is currently dependent on a specific version of node-fetch. To enhance compatibility and ease future maintenance, I propose updating the project to require a minimum of Node.js v18 and using node-fetch as a polyfill, leveraging Node.js's native fetch support in version 18 and above.

### Proposed Changes

1. Set Minimum Node.js Version to v18

Node.js v18 is the earliest LTS version in Maintenance, providing long-term support and stability. Requiring Node.js v18 or newer will simplify dependencies and align the project with the latest stable standards.

2. Use node-fetch as a Polyfill

Since Node.js v18 supports the native fetch API, we can avoid pinning a specific version of node-fetch by only using it as a polyfill, ensuring smooth compatibility for environments lacking native fetch.

### Next Steps
If the proposed changes align with the project goals, I would be happy to open a pull request implementing these updates.

**Comment by agisboye** [comment]
Thanks for the proposal!
I think it's about time we set the minimum version to v18. 

If fetch is natively supported, why do we even need `node-fetch`? Is it because the API was not marked stable until v21?

**Comment by KROSF** [comment]
We don't require it at all, but some users may want to use the library on unsupported versions. To assist them, we can provide an example that demonstrates how to add a polyfill for fetch using node-fetch:

```js
import fetch from "node-fetch";

global.fetch = fetch;
```

**Comment by agisboye** [comment]
Thanks for your contribution!
