### ISSUE TITLE
Add all (or more) types as default exports

### ISSUE THREAD

**Issue by biancadanforth** [agisboye/app-store-server-api#6]
Firstly, thank you very much for creating this API client library.

One issue I encountered when using the library is that not every type that our code uses is part of the default exports in [`src/index.ts`](https://github.com/agisboye/app-store-server-api/blob/33c466733a223974e077264a525ef36c4324f5de/src/index.ts#L1-L17).

In particular, we are currently using or plan to use the following types which are not part of the library's default exports:
* JWSTransactionDecodedPayload
* OwnershipType
* TransactionType
* StatusResponse
* LastTransactionsItem
* JWSRenewalInfoDecodedPayload

And in general, others that could be useful that are not default exported:
* HistoryResponse
* SubscriptionGroupIdentifierItem
* OrderLookupResponse

Can these types be added to the default exports in `src/index.ts`? I plan to open a PR to this effect shortly for your consideration.

**Comment by agisboye** [comment]
Thanks for the PR! I've merged it and tagged it as [v0.3.0](https://github.com/agisboye/app-store-server-api/releases/tag/v0.3.0).
